### ISSUE TITLE
Issue upon forcing channel update

### ISSUE THREAD

**Issue by gils001** [fnord12/script.pseudotv#4]
Set to force channel update and launched Pseudo but it crashed while updating
Here is the log:
`2020-05-30 04:09:09.015 T:13407   ERROR: NEWADDON Unknown Video Info Key "progress"
2020-05-30 04:09:13.844 T:13436   ERROR: Previous line repeats 38 times.
2020-05-30 04:09:13.845 T:13436   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 225, in onInit
                                                if self.readConfig() == False:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 328, in readConfig
                                                self.channels = self.channelList.setupList()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/ChannelList.py", line 127, in setupList
                                                self.setupChannel(i + 1, False, makenewlists, False)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/ChannelList.py", line 303, in setupChannel
                                                if self.makeChannelList(channel, chtype, chsetting1, chsetting2, append) == True:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/ChannelList.py", line 525, in makeChannelList
                                                fileList = self.runActions(RULES_ACTION_LIST, channel, fileList)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/ChannelList.py", line 1251, in runActions
                                                parameter = rule.runAction(action, self, parameter)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/Rules.py", line 1002, in runAction
                                                channelList.setupChannel(chan, True, True, False)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/ChannelList.py", line 303, in setupChannel
                                                if self.makeChannelList(channel, chtype, chsetting1, chsetting2, append) == True:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/ChannelList.py", line 459, in makeChannelList
                                                fileList = self.createDirectoryPlaylist(setting1)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/ChannelList.py", line 743, in createDirectoryPlaylist
                                                ChannelName = Pathlist[-2]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-05-30 04:09:37.557 T:13364  NOTICE: CWinSystemAndroid::DestroyWindow
2020-05-30 04:09:37.563 T:13343 WARNING: CPeripheralBusAndroid: failed to update input device with ID -3 because it couldn't be found
`

**Comment by fnord12** [comment]
This is due to a bad assumption i made about file paths. Sorry!  I should have a fix later today.  If you want to keep playing with my version, you can disable your Directory channels for the time being.

**Comment by gils001** [comment]
No problem I can wait till then. Thanks for replying!

**Comment by fnord12** [comment]
This should be fixed but let me sure as i can't currently test in your OS.

**Comment by gils001** [comment]
Looks good I was able to successfully update my channels and launch PseudoTV without crashing
